# tasks file for nano, improved nanorc
---
- name: improved nanorc | install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ nano_improved_nanorc_dependencies }}"
  tags:
    - nano-improved-nanorc-dependencies

- name: improved nanorc | create (checkout) directory
  file:
    path: /var/lib/ansible/nano/checkouts
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - nano-improved-nanorc-checkout

- name: improved nanorc | checkout repository
  git:
    repo: "{{ nano_improved_nanorc_git_repo }}"
    dest: /var/lib/ansible/nano/checkouts/nanorc
    version: "{{ nano_improved_nanorc_git_branch }}"
    force: true
  register: result
  tags:
    - nano-improved-nanorc-checkout

- name: improved nanorc | install syntax definitions
  shell: "make install-global && make clean"
  args:
    chdir: "/var/lib/ansible/nano/checkouts/nanorc"
  when: result | changed
  tags:
    - nano-improved-nanorc-install
