# tasks file for nano, improved nanorc
---
- name: improved nanorc | install dependencies
  apt:
    name: "{{ nano_improved_nanorc_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nano-improved-nanorc-dependencies

- name: improved nanorc | create (checkout) directory
  file:
    path: "{{ nano_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - nano-improved-nanorc-checkout

- name: improved nanorc | checkout repository
  git:
    repo: "{{ nano_improved_nanorc_git_repo }}"
    dest: "{{ nano_checkout_path }}"
    version: "{{ nano_improved_nanorc_git_branch }}"
    force: true
  register: _result
  tags:
    - nano-improved-nanorc-checkout

- name: improved nanorc | install syntax definitions
  shell: >
    make install-global && make clean
  args:
    chdir: "{{ nano_checkout_path }}"
  when: _result is changed
  tags:
    - nano-improved-nanorc-install
